export enum OPCode {
  DISPATCH = 0,
  HEARTBEAT = 1,
  IDENTIFY = 2,
  PRESENCE_UPDATE = 3,
  VOICE_STATE_UPDATE = 4,
  RESUME = 5,
  RECONNECT = 7,
  REQUEST_GUILD_MEMBERS = 8,
  INVALID_SESSION = 9,
  HELLO = 10,
  HEARTBEAT_ACK = 11,
}

export enum DiscordPresenceStatus {
  ONLINE = 'online',
  DND = 'dnd',
  IDLE = 'idle',
  INVISIBLE = 'invisible',
  OFFLINE = 'offline',
}

export enum GatewayMessageType {
  HELLO = 'HELLO',
  READY = 'READY',
  RESUMED = 'RESUMED',
  RECONNECT = 'RECONNECT',
  INVALID_SESSION = 'INVALID_SESSION',
  CHANNEL_CREATE = 'CHANNEL_CREATE',
  CHANNEL_UPDATE = 'CHANNEL_UPDATE',
  CHANNEL_DELETE = 'CHANNEL_DELETE',
  CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE',
  MESSAGE_CREATE = 'MESSAGE_CREATE',
  MESSAGE_UPDATE = 'MESSAGE_UPDATE',
  MESSAGE_DELETE = 'MESSAGE_DELETE',
  MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK',
  MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD',
  MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE',
  MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL',
  MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI',
  MESSAGE_ACK = 'MESSAGE_ACK',
  PRESENCE_UPDATE = 'PRESENCE_UPDATE',
  TYPING_START = 'TYPING_START',
  USER_UPDATE = 'USER_UPDATE',
  RELATIONSHIP_ADD = 'RELATIONSHIP_ADD',
  RELATIONSHIP_REMOVE = 'RELATIONSHIP_REMOVE'
}
