// https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-opcodes
export enum OPCode {
  DISPATCH = 0,
  HEARTBEAT = 1,
  IDENTIFY = 2,
  PRESENCE_UPDATE = 3,
  VOICE_STATE_UPDATE = 4,
  // 5 is undefined
  RESUME = 6,
  RECONNECT = 7,
  REQUEST_GUILD_MEMBERS = 8,
  INVALID_SESSION = 9,
  HELLO = 10,
  HEARTBEAT_ACK = 11,
}

export enum DiscordPresenceStatus {
  ONLINE = 'online',
  DND = 'dnd',
  IDLE = 'idle',
  INVISIBLE = 'invisible',
  OFFLINE = 'offline',
}

export enum GatewayMessageType {
  HELLO = 'HELLO',
  READY = 'READY',
  RESUMED = 'RESUMED',
  RECONNECT = 'RECONNECT',
  INVALID_SESSION = 'INVALID_SESSION',
  CHANNEL_CREATE = 'CHANNEL_CREATE',
  CHANNEL_UPDATE = 'CHANNEL_UPDATE',
  CHANNEL_DELETE = 'CHANNEL_DELETE',
  CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE',
  CHANNEL_UNREAD_UPDATE = 'CHANNEL_UNREAD_UPDATE',
  MESSAGE_CREATE = 'MESSAGE_CREATE',
  MESSAGE_UPDATE = 'MESSAGE_UPDATE',
  MESSAGE_DELETE = 'MESSAGE_DELETE',
  MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK',
  MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD',
  MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE',
  MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL',
  MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI',
  MESSAGE_ACK = 'MESSAGE_ACK',
  PRESENCE_UPDATE = 'PRESENCE_UPDATE',
  TYPING_START = 'TYPING_START',
  USER_UPDATE = 'USER_UPDATE',
  USER_SETTINGS_UPDATE = 'USER_SETTINGS_UPDATE',
  RELATIONSHIP_ADD = 'RELATIONSHIP_ADD',
  RELATIONSHIP_REMOVE = 'RELATIONSHIP_REMOVE',

  // ACT_AS_USER
  GUILD_CREATE = 'GUILD_CREATE',
  GUILD_UPDATE = 'GUILD_UPDATE',
  GUILD_DELETE = 'GUILD_DELETE',
  GUILD_BAN_ADD = 'GUILD_BAN_ADD',
  GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE',
  READY_SUPPLEMENTAL = 'READY_SUPPLEMENTAL',
  VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE',
}

export enum GatewayCloseCode {
  RECONNECT_REQUESTED = 1001,
  DISCONNECTED = 1005,
  ADDRESS_NOT_FOUND = 1006,
  UNKNOWN_ERROR = 4000,
  UNKNOWN_OPCODE = 4001,
  DECODE_ERROR = 4002,
  NOT_AUTHENTICATED = 4003,
  AUTHENTICATION_FAILED = 4004,
  ALREADY_AUTHENTICATED = 4005,
  INVALID_SEQ = 4007,
  RATE_LIMITED = 4008,
  SESSION_TIMED_OUT = 4009,
  INVALID_API_VERSION = 4012,
  INVALID_INTENTS = 4013,
  DISALLOWED_INTENTS = 4014,
}
